language: node_js
node_js:
  - 12

services:
  - docker

before_script: ./install-dcompose.sh

script:
  - docker-compose build
  - docker-compose run api npm run build
  - docker-compose run api npm run test
