language: node_js
node_js:
  - 12

services:
  - docker

before_script: sudo apt install docker-compose

script:
  - docker-compose build
  - docker-compose npm run build
  - docker-compose run api npm run test
