language: node_js
dist: xenial
node_js:
  - 12

services:
  - docker

stages:
  - test

jobs:
  include:
    - stage: test
      if: type = pull_request
      install: ./install-dcompose.sh
      script:
        - docker-compose build
        - docker-compose run api npm run format
        - docker-compose run api npm run lint
        - docker-compose run api npm run build
        - docker-compose run api npm run test
