language: node_js
dist: xenial
node_js:
  - 12

services:
  - docker

stages:
  - test

jobs:
  include:
    - stage: test
      if: type = pull_request
      before_script: ./install-dcompose.sh
      script:
        - docker-compose build
        - docker-compose run api npm run build
        - docker-compose run api npm run test
# before_script: ./install-dcompose.sh

# script:
#   - docker-compose build
#   - docker-compose run api npm run build
#   - docker-compose run api npm run test
