version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: '${ORM_USERNAME}'
      POSTGRES_PASSWORD: '${ORM_PASSWORD}'
      POSTGRES_MULTIPLE_DATABASES: '${ORM_DATABASE},${ORM_TEST_DATABASE}'
    ports:
      - '5434:5432'
    volumes:
      - ./pg-init-scripts/:/docker-entrypoint-initdb.d/
      - ~/movie-rental/data_volume:/var/lib/postgresql/data
  api:
    build: .
    command: npm run start:dev
    # environment:
    #   ORM_HOST: '${ORM_HOST}'
    #   ORM_CONNECTION: '${ORM_CONNECTION}'
    #   ORM_HOST: '${ORM_HOST}'
    #   ORM_USERNAME: '${ORM_USERNAME}'
    #   ORM_PASSWORD: '${ORM_PASSWORD}'
    #   ORM_DATABASE: '${ORM_DATABASE}'
    #   ORM_TEST_DATABASE: '${ORM_TEST_DATABASE}'
    #   ORM_PORT: '${ORM_PORT}'
    #   ORM_SYNCHRONIZE: '${ORM_SYNCHRONIZE}'
    #   ORM_ENTITIES: '${ORM_ENTITIES}'
    #   ORM_MIGRATIONS_TABLE_NAME: '${ORM_MIGRATIONS_TABLE_NAME}'
    #   ORM_MIGRATIONS: '${ORM_MIGRATIONS}'
    #   ORM_MIGRATIONS_DIR: '${ORM_MIGRATIONS_DIR}'
    #   ORM_MIGRATIONS_RUN: '${ORM_MIGRATIONS_RUN}'
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file: .env
